#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
#  if [ -x "$(command -v feh)" ]; then
#   feh --bg-scale $SCRIPTPATH/background.jpg
#  fi

#boot pnmixer exists
# if [ -x "$(command -v pnmixer)" ]; then
#   pnmixer &
# fi

#boot flameshot exists
if [ -x "$(command -v flameshot)" ]; then
  flameshot &
fi
if [ -x "$(command -v blueman-applet)" ]; then
  blueman-applet &
fi

# startup apps
 /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
nitrogen --restore &
xfce4-power-manager &
lxpolkit &

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done

